### ISSUE TITLE
Hints (née Training-Wheels) Utility

### ISSUE THREAD

**Issue by csswizardry** [NHSLeadership/nightingale#109]
It’s possible to write some pretty automatic CSS that can be used to lint our HTML structure to ensure that we’re using things like grids properly. This means that—as we learn about how Nightingale works—we’ll get helpful hints in the browser if we inadvertently do things incorrectly.

Happy to work on a different name if people find this one patronising. Just wanted to come up with something quickly.

**Comment by Android63** [comment]
I like the name  - although something like "hints" might be more generally acceptable.

**Comment by csswizardry** [comment]
As an example, if someone forgets to wrap an `.o-layout__item` element inside of its `.o-layout` parent, we can display an error like so:

![image](https://user-images.githubusercontent.com/751944/28323375-82265d34-6bd0-11e7-915a-fe8552005cfd.png)

The Sass inside of `training-wheels.scss`:

```scss
/**
 * Layout Items must be nested directly within an `.o-layout` parent.
 */
.o-layout__item {
  --error: "Yikes! This needs to live inside of an `.o-layout` parent.";
  outline: 1px solid red;

  .o-layout > & {
    outline: none;
  }

}
```
