### ISSUE TITLE
Revisit Link Styles

### ISSUE THREAD

**Issue by csswizardry** [NHSLeadership/nightingale#128]
I’d like a tech debt task to take another look at how links are being implemented. Currently, I’m getting a lot of conflicts with `a:visited` styles overriding things like `.c-btn`, etc., plus there feels to be some confusion about conventions with blue unvisited vs. current states.

Also, maybe look at how external links are styled:

```css
a:not([href*="localhost"]):not([href^="#"]):not([href^="/"])::after,
.u-link-external {}
```
